// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: carts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCart = `-- name: CreateCart :one
INSERT INTO carts (id ,  user_id, status , created_at , updated_at) 
VALUES ($1,$2,$3,$4 ,$5 )

RETURNING id, user_id, status, created_at, updated_at
`

type CreateCartParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByUserId = `-- name: GetCartByUserId :one
SELECT id, user_id, status, created_at, updated_at FROM carts WHERE user_id = $1
`

func (q *Queries) GetCartByUserId(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartByUserId, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
