// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: carts_items.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (id ,  cart_id , product_id,quantity,price_at_add , created_at , updated_at) 
VALUES ($1,$2,$3,$4 ,$5,$6,$7)

RETURNING id, cart_id, product_id, quantity, price_at_add, created_at, updated_at
`

type CreateCartItemParams struct {
	ID         uuid.UUID
	CartID     uuid.UUID
	ProductID  uuid.UUID
	Quantity   int32
	PriceAtAdd string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, createCartItem,
		arg.ID,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtAdd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtAdd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByCartId = `-- name: GetCartItemByCartId :many
SELECT id, cart_id, product_id, quantity, price_at_add, created_at, updated_at FROM cart_items WHERE cart_id = $1
`

func (q *Queries) GetCartItemByCartId(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, getCartItemByCartId, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceAtAdd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItemByCartIdAndProductId = `-- name: GetCartItemByCartIdAndProductId :one
SELECT id, cart_id, product_id, quantity, price_at_add, created_at, updated_at FROM cart_items WHERE cart_id = $1 and product_id = $2
`

type GetCartItemByCartIdAndProductIdParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartItemByCartIdAndProductId(ctx context.Context, arg GetCartItemByCartIdAndProductIdParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByCartIdAndProductId, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtAdd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items SET quantity = $1 WHERE id = $2

RETURNING id, cart_id, product_id, quantity, price_at_add, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	Quantity int32
	ID       uuid.UUID
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, updateCartItemQuantity, arg.Quantity, arg.ID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtAdd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
