// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCategoty = `-- name: CreateCategoty :one
INSERT INTO categories (id ,  name, description ,parent_id, created_at , updated_at) 
VALUES ($1,$2,$3,$4 ,$5 ,$6)
RETURNING id, name, description, parent_id, created_at, updated_at
`

type CreateCategotyParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	ParentID    uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateCategoty(ctx context.Context, arg CreateCategotyParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategoty,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
