// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type CartItem struct {
	ID         uuid.UUID
	CartID     uuid.UUID
	ProductID  uuid.UUID
	Quantity   int32
	PriceAtAdd string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Category struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	ParentID    uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Order struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrderStatus    string
	Total          string
	PaymentStatus  sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	PaymentMethod  sql.NullString
	DeliveryStatus sql.NullString
}

type OrderItem struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	ProductID  uuid.UUID
	Quantity   int32
	UnitPrice  string
	TotalPrice string
	CreatedAt  sql.NullTime
}

type Otp struct {
	ID        uuid.UUID
	Otp       string
	UserID    uuid.UUID
	ExpAt     time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       int32
	CategoryID  uuid.UUID
	ImageUrl    sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt sql.NullTime
}

type ShippingAddress struct {
	ID                   uuid.UUID
	OrderID              uuid.UUID
	FullName             string
	Phone                string
	AddressLine1         string
	AddressLine2         sql.NullString
	City                 string
	State                string
	PostalCode           string
	Country              string
	DeliveryInstructions sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type TokenBlacklist struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	IsAdmin   bool
	CreatedAt time.Time
	UpdatedAt time.Time
	Phone     sql.NullString
}
