// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id , user_id , order_status , total ,payment_status, created_at , updated_at) 
values($1,$2,$3,$4,$5,$6 , $7)
RETURNING id, user_id, order_status, total, payment_status, created_at, updated_at
`

type CreateOrderParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	OrderStatus   string
	Total         string
	PaymentStatus sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.OrderStatus,
		arg.Total,
		arg.PaymentStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderStatus,
		&i.Total,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
