// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id ,  name, description ,price,stock,category_id,image_url,is_active, created_at , updated_at) 
VALUES ($1,$2,$3,$4 ,$5 ,$6,$7,$8 ,$9 ,$10)

RETURNING id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector
`

type CreateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       int32
	CategoryID  uuid.UUID
	ImageUrl    sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
		arg.ImageUrl,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const deleteProductByProductId = `-- name: DeleteProductByProductId :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProductByProductId(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductByProductId, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByCategoryId = `-- name: GetProductByCategoryId :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products WHERE category_id = $1
`

func (q *Queries) GetProductByCategoryId(ctx context.Context, categoryID uuid.UUID) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductByCategoryId, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByCategoryIdAndPriceRange = `-- name: GetProductByCategoryIdAndPriceRange :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products WHERE category_id = $1 AND price >= $2 AND price <= $3
`

type GetProductByCategoryIdAndPriceRangeParams struct {
	CategoryID uuid.UUID
	Price      string
	Price_2    string
}

func (q *Queries) GetProductByCategoryIdAndPriceRange(ctx context.Context, arg GetProductByCategoryIdAndPriceRangeParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductByCategoryIdAndPriceRange, arg.CategoryID, arg.Price, arg.Price_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products WHERE id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products WHERE name = $1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getProductByPriceRange = `-- name: GetProductByPriceRange :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products WHERE price >= $1 AND price <= $2
`

type GetProductByPriceRangeParams struct {
	Price   string
	Price_2 string
}

func (q *Queries) GetProductByPriceRange(ctx context.Context, arg GetProductByPriceRangeParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductByPriceRange, arg.Price, arg.Price_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsPerPage = `-- name: GetProductsPerPage :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products ORDER BY created_at ASC Limit $1
`

func (q *Queries) GetProductsPerPage(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductsPerPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductImage = `-- name: UpdateProductImage :one
UPDATE products SET image_url = $1 WHERE id = $2
RETURNING id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector
`

type UpdateProductImageParams struct {
	ImageUrl sql.NullString
	ID       uuid.UUID
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductImage, arg.ImageUrl, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const updateProductPrice = `-- name: UpdateProductPrice :one
UPDATE products SET price = $1 WHERE id = $2
RETURNING id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector
`

type UpdateProductPriceParams struct {
	Price string
	ID    uuid.UUID
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductPrice, arg.Price, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products SET stock = $1 WHERE id = $2
RETURNING id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector
`

type UpdateProductStockParams struct {
	Stock int32
	ID    uuid.UUID
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStock, arg.Stock, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
