// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: search.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const autocompleteProductName = `-- name: AutocompleteProductName :many
SELECT DISTINCT name FROM products
WHERE name ILIKE $1 || '%'
  AND is_active = true
ORDER BY name
LIMIT 10
`

// Fast product name autocomplete using trigram index
func (q *Queries) AutocompleteProductName(ctx context.Context, dollar_1 sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, autocompleteProductName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fuzzySearchProducts = `-- name: FuzzySearchProducts :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products 
WHERE name % $1  -- Similarity operator
  AND is_active = true
  AND stock > 0
ORDER BY similarity(name, $1) DESC
LIMIT $2
`

type FuzzySearchProductsParams struct {
	Name  string
	Limit int32
}

// Fuzzy search for typo tolerance (e.g., "iphon" finds "iphone")
func (q *Queries) FuzzySearchProducts(ctx context.Context, arg FuzzySearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, fuzzySearchProducts, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCODPendingDeliveries = `-- name: GetCODPendingDeliveries :many
SELECT o.id, o.user_id, o.order_status, o.total, o.payment_status, o.created_at, o.updated_at, o.payment_method, o.delivery_status, sa.id, sa.order_id, sa.full_name, sa.phone, sa.address_line1, sa.address_line2, sa.city, sa.state, sa.postal_code, sa.country, sa.delivery_instructions, sa.created_at, sa.updated_at 
FROM orders o
INNER JOIN shipping_addresses sa ON o.id = sa.order_id
WHERE o.payment_method = 'cod' 
  AND o.delivery_status = 'confirmed' 
  AND o.payment_status = 'pending'
ORDER BY o.created_at ASC
`

type GetCODPendingDeliveriesRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	OrderStatus          string
	Total                string
	PaymentStatus        sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	PaymentMethod        sql.NullString
	DeliveryStatus       sql.NullString
	ID_2                 uuid.UUID
	OrderID              uuid.UUID
	FullName             string
	Phone                string
	AddressLine1         string
	AddressLine2         sql.NullString
	City                 string
	State                string
	PostalCode           string
	Country              string
	DeliveryInstructions sql.NullString
	CreatedAt_2          sql.NullTime
	UpdatedAt_2          sql.NullTime
}

// Uses the partial index idx_orders_cod_pending
func (q *Queries) GetCODPendingDeliveries(ctx context.Context) ([]GetCODPendingDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCODPendingDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCODPendingDeliveriesRow
	for rows.Next() {
		var i GetCODPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderStatus,
			&i.Total,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaymentMethod,
			&i.DeliveryStatus,
			&i.ID_2,
			&i.OrderID,
			&i.FullName,
			&i.Phone,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.DeliveryInstructions,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLowStockProducts = `-- name: GetLowStockProducts :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products
WHERE stock > 0 AND stock <= $1
  AND is_active = true
ORDER BY stock ASC
`

// Uses partial index on stock
func (q *Queries) GetLowStockProducts(ctx context.Context, stock int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getLowStockProducts, stock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByGeography = `-- name: GetOrdersByGeography :many
SELECT o.id, o.user_id, o.order_status, o.total, o.payment_status, o.created_at, o.updated_at, o.payment_method, o.delivery_status, sa.id, sa.order_id, sa.full_name, sa.phone, sa.address_line1, sa.address_line2, sa.city, sa.state, sa.postal_code, sa.country, sa.delivery_instructions, sa.created_at, sa.updated_at
FROM orders o
INNER JOIN shipping_addresses sa ON o.id = sa.order_id
WHERE sa.city = $1 
  AND sa.state = $2
ORDER BY o.created_at DESC
`

type GetOrdersByGeographyParams struct {
	City  string
	State string
}

type GetOrdersByGeographyRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	OrderStatus          string
	Total                string
	PaymentStatus        sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	PaymentMethod        sql.NullString
	DeliveryStatus       sql.NullString
	ID_2                 uuid.UUID
	OrderID              uuid.UUID
	FullName             string
	Phone                string
	AddressLine1         string
	AddressLine2         sql.NullString
	City                 string
	State                string
	PostalCode           string
	Country              string
	DeliveryInstructions sql.NullString
	CreatedAt_2          sql.NullTime
	UpdatedAt_2          sql.NullTime
}

// Uses idx_shipping_addresses_city_state
func (q *Queries) GetOrdersByGeography(ctx context.Context, arg GetOrdersByGeographyParams) ([]GetOrdersByGeographyRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByGeography, arg.City, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByGeographyRow
	for rows.Next() {
		var i GetOrdersByGeographyRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderStatus,
			&i.Total,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaymentMethod,
			&i.DeliveryStatus,
			&i.ID_2,
			&i.OrderID,
			&i.FullName,
			&i.Phone,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.DeliveryInstructions,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularProducts = `-- name: GetPopularProducts :many
SELECT 
    p.id, p.name, p.description, p.price, p.stock, p.category_id, p.image_url, p.is_active, p.created_at, p.updated_at, p.search_vector,
    COUNT(oi.id) as order_count,
    SUM(oi.quantity) as total_quantity_sold
FROM products p
INNER JOIN order_items oi ON p.id = oi.product_id
WHERE p.is_active = true
GROUP BY p.id
ORDER BY order_count DESC
LIMIT $1
`

type GetPopularProductsRow struct {
	ID                uuid.UUID
	Name              string
	Description       sql.NullString
	Price             string
	Stock             int32
	CategoryID        uuid.UUID
	ImageUrl          sql.NullString
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	SearchVector      interface{}
	OrderCount        int64
	TotalQuantitySold int64
}

// Get most ordered products (uses order_items index)
func (q *Queries) GetPopularProducts(ctx context.Context, limit int32) ([]GetPopularProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPopularProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularProductsRow
	for rows.Next() {
		var i GetPopularProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.OrderCount,
			&i.TotalQuantitySold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecentOrders = `-- name: GetUserRecentOrders :many
SELECT id, user_id, order_status, total, payment_status, created_at, updated_at, payment_method, delivery_status FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetUserRecentOrdersParams struct {
	UserID uuid.UUID
	Limit  int32
}

// Uses composite index idx_orders_user_recent
func (q *Queries) GetUserRecentOrders(ctx context.Context, arg GetUserRecentOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecentOrders, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderStatus,
			&i.Total,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaymentMethod,
			&i.DeliveryStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products 
WHERE search_vector @@ plainto_tsquery('english', $1)
  AND is_active = true
  AND stock > 0
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $1)) DESC
LIMIT $2
`

type SearchProductsParams struct {
	PlaintoTsquery string
	Limit          int32
}

// Full-text search on products
func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsByCategoryAndPrice = `-- name: SearchProductsByCategoryAndPrice :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products
WHERE category_id = $1
  AND price >= $2
  AND price <= $3
  AND is_active = true
  AND stock > 0
ORDER BY price ASC
`

type SearchProductsByCategoryAndPriceParams struct {
	CategoryID uuid.UUID
	Price      string
	Price_2    string
}

// Uses composite index on category_id and price
func (q *Queries) SearchProductsByCategoryAndPrice(ctx context.Context, arg SearchProductsByCategoryAndPriceParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProductsByCategoryAndPrice, arg.CategoryID, arg.Price, arg.Price_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsByPriceRange = `-- name: SearchProductsByPriceRange :many
SELECT id, name, description, price, stock, category_id, image_url, is_active, created_at, updated_at, search_vector FROM products
WHERE price >= $1 
  AND price <= $2
  AND is_active = true
  AND stock > 0
ORDER BY price ASC
LIMIT $3
`

type SearchProductsByPriceRangeParams struct {
	Price   string
	Price_2 string
	Limit   int32
}

// Optimized price range search using index
func (q *Queries) SearchProductsByPriceRange(ctx context.Context, arg SearchProductsByPriceRangeParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProductsByPriceRange, arg.Price, arg.Price_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT id, name, email, phone, is_admin, created_at
FROM users
WHERE name % $1
ORDER BY similarity(name, $1) DESC
LIMIT $2
`

type SearchUsersByNameParams struct {
	Name  string
	Limit int32
}

type SearchUsersByNameRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Phone     sql.NullString
	IsAdmin   bool
	CreatedAt time.Time
}

// Fuzzy search users by name (for admin panel)
func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]SearchUsersByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersByNameRow
	for rows.Next() {
		var i SearchUsersByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
