// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shipping_addresses.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createShippingAddress = `-- name: CreateShippingAddress :one
INSERT INTO shipping_addresses(
    id,
    order_id,
    full_name,
    phone,
    address_line1,
    address_line2,
    city,
    state,
    postal_code,
    country,
    delivery_instructions,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, order_id, full_name, phone, address_line1, address_line2, city, state, postal_code, country, delivery_instructions, created_at, updated_at
`

type CreateShippingAddressParams struct {
	ID                   uuid.UUID
	OrderID              uuid.UUID
	FullName             string
	Phone                string
	AddressLine1         string
	AddressLine2         sql.NullString
	City                 string
	State                string
	PostalCode           string
	Country              string
	DeliveryInstructions sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

func (q *Queries) CreateShippingAddress(ctx context.Context, arg CreateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, createShippingAddress,
		arg.ID,
		arg.OrderID,
		arg.FullName,
		arg.Phone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.DeliveryInstructions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FullName,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.DeliveryInstructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShippingAddress = `-- name: DeleteShippingAddress :exec
DELETE FROM shipping_addresses
WHERE id = $1
`

func (q *Queries) DeleteShippingAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShippingAddress, id)
	return err
}

const getShippingAddressByOrderId = `-- name: GetShippingAddressByOrderId :one
SELECT id, order_id, full_name, phone, address_line1, address_line2, city, state, postal_code, country, delivery_instructions, created_at, updated_at FROM shipping_addresses
WHERE order_id = $1
`

func (q *Queries) GetShippingAddressByOrderId(ctx context.Context, orderID uuid.UUID) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, getShippingAddressByOrderId, orderID)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FullName,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.DeliveryInstructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShippingAddress = `-- name: UpdateShippingAddress :one
UPDATE shipping_addresses
SET 
    full_name = $2,
    phone = $3,
    address_line1 = $4,
    address_line2 = $5,
    city = $6,
    state = $7,
    postal_code = $8,
    country = $9,
    delivery_instructions = $10,
    updated_at = $11
WHERE id = $1
RETURNING id, order_id, full_name, phone, address_line1, address_line2, city, state, postal_code, country, delivery_instructions, created_at, updated_at
`

type UpdateShippingAddressParams struct {
	ID                   uuid.UUID
	FullName             string
	Phone                string
	AddressLine1         string
	AddressLine2         sql.NullString
	City                 string
	State                string
	PostalCode           string
	Country              string
	DeliveryInstructions sql.NullString
	UpdatedAt            sql.NullTime
}

func (q *Queries) UpdateShippingAddress(ctx context.Context, arg UpdateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, updateShippingAddress,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.DeliveryInstructions,
		arg.UpdatedAt,
	)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FullName,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.DeliveryInstructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
