// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: token_blacklist.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTokenBlacklist = `-- name: CreateTokenBlacklist :one
INSERT INTO token_blacklist (id, user_id, token, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateTokenBlacklistParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateTokenBlacklist(ctx context.Context, arg CreateTokenBlacklistParams) (TokenBlacklist, error) {
	row := q.db.QueryRowContext(ctx, createTokenBlacklist,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i TokenBlacklist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredBlacklistTokens = `-- name: DeleteExpiredBlacklistTokens :exec
DELETE FROM token_blacklist
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredBlacklistTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBlacklistTokens)
	return err
}
