// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id ,  name, email ,password, phone, is_admin, created_at , updated_at) 
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)

RETURNING id, name, email, password, is_admin, created_at, updated_at, phone
`

type CreateUserParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Phone     sql.NullString
	IsAdmin   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const deleteUserByUserId = `-- name: DeleteUserByUserId :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByUserId(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUserId, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, is_admin, created_at, updated_at, phone FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, password, is_admin, created_at, updated_at, phone FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const updateUserPasword = `-- name: UpdateUserPasword :one
UPDATE users SET password = $1 WHERE id = $2
RETURNING id, name, email, password, is_admin, created_at, updated_at, phone
`

type UpdateUserPaswordParams struct {
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdateUserPasword(ctx context.Context, arg UpdateUserPaswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPasword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE users SET phone = $1, updated_at = $3 WHERE id = $2
RETURNING id, name, email, password, is_admin, created_at, updated_at, phone
`

type UpdateUserPhoneParams struct {
	Phone     sql.NullString
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPhone, arg.Phone, arg.ID, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
	)
	return i, err
}
